spring:
  application:
    name: ledger-service

  datasource:
    url: jdbc:postgresql://localhost:5436/ledger_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ledger-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.proj.events"
        spring.json.value.default.type: "com.proj.events.TransactionEvent"

server:
  port: 8084

ledger:
  topic: ledger.transactions

jwt:
  secret: ${JWT_SECRET:change-this-to-a-long-random-secret-value-at-least-32-bytes}
