apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: banking/wallet:latest
          ports:
            - containerPort: 8080
            - containerPort: 9091
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/wallet_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banking-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: banking-secrets
                  key: JWT_SECRET
            - name: GRPC_USER_ADDRESS
              value: dns:///user-service:9090
          readinessProbe:
            tcpSocket:
              port: 9091
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 9091
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
spec:
  clusterIP: None
  selector:
    app: wallet-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9091
      targetPort: 9091
